version: 1.3.{build}
configuration: Release
before_build:
- cmd: >-
    dotnet restore
    dotnet build
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: Marco.Exceptions.Core
deploy:
- provider: NuGet
  api_key:
    secure: RCtjjLPpGMVjt4mD8LurHJ9fhXCmpZwOH6HKXTh34VoN2sjJUvX56WrHzv8OA6MG
  username:
    secure: bYlevw9glkB8gEUc3o9Trg==
- provider: GitHub
  auth_token:
    secure: ek1fk5tcMcP769bm8uV/8j2u4/FOvnPVF33wSuOyAHJ9W56zvwm7ABQ0ho4TEEEV
  prerelease: false
  force_update: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
